export const normalizeDropdownValue = (field, value) => {
  if (!value) return "";
  const normalizedValue = value.toString().trim();
  console.log(`Normalize [${field}]: '${value}' -> '${normalizedValue}'`); // DEBUG LOG

  const mappings = {
    // Gender
    gender: {
      "ஆண்": "Male",
      "பெண்": "Female",
      "மற்றவை": "Other"
    },
    // Dasa Type
    DasaType: {
      "சூரிய மகா திசை": "சூரிய மகா திசை-Surya Maga Dasa", "Surya Maga Dasa": "சூரிய மகா திசை-Surya Maga Dasa",
      "சந்திர மகா திசை": "சந்திர மகா திசை-Chandhira Maga Dasa", "Chandhira Maga Dasa": "சந்திர மகா திசை-Chandhira Maga Dasa",
      "செவ்வாய் மகா திசை": "செவ்வாய் மகா திசை-Sevvaai Maga Dasa", "Sevvaai Maga Dasa": "செவ்வாய் மகா திசை-Sevvaai Maga Dasa",
      "புதன் மகா திசை": "புதன் மகா திசை-Budhan Maga Dasa", "Budhan Maga Dasa": "புதன் மகா திசை-Budhan Maga Dasa",
      "வியாழ மகா திசை": "வியாழ மகா திசை-Viyaazha Maga Dasa", "Viyaazha Maga Dasa": "வியாழ மகா திசை-Viyaazha Maga Dasa",
      "சுக்கிர மகா திசை": "சுக்கிர மகா திசை-Sukkran Maga Dasa", "Sukkran Maga Dasa": "சுக்கிர மகா திசை-Sukkran Maga Dasa",
      "சனி மகா திசை": "சனி மகா திசை-Sani Maga Dasa", "Sani Maga Dasa": "சனி மகா திசை-Sani Maga Dasa",
      "ராகு மகா திசை": "ராகு மகா திசை-Raagu Maga Dasa", "Raagu Maga Dasa": "ராகு மகா திசை-Raagu Maga Dasa",
      "கேது மகா திசை": "கேது மகா திசை-Kethu Maga Dasa", "Kethu Maga Dasa": "கேது மகா திசை-Kethu Maga Dasa"
    },
    // Weight (Simple stripper for common localized suffixes if present, though likely numeric in DB)
    weight: {
       // Ideally weight is just a number + " kg". If localized to "25 கிலோ", we map it.
       // Generating basic map for 25-130kg if needed, or better, regex stripper in future.
       // For now, assuming exact string match is safer.
    },


    // Body Type / Complexion
    complexion: {
      "நல்ல சிவப்பு": "Fair red / Bright red (nalla sivappu)",
      "சிவப்பு": "Red (sivappu)",
      "மாநிறம்": "Wheatish (maaniram)",
      "கருப்பு": "Black (karuppu)",
      // Fallbacks from previous guesses just in case
      "மிகவும் சிகப்பு": "Fair red / Bright red (nalla sivappu)",
      "சிகப்பு": "Red (sivappu)",
      "மீடியம்": "Wheatish (maaniram)",
      "கருமை": "Black (karuppu)",
      "கோதுமை": "Wheatish (maaniram)" 
    },
    // Diet
    diet: {
      "சைவம்": "Vegetarian",
      "அசைவம்": "Non-Vegetarian",
      "முட்டை மட்டும்": "Eggetarian"
    },
    // Partner Pref - Willingness to work
    // Partner Pref - Willingness to work
    willingnessToWork: {
      "விருப்பமில்லை": "No", "Not Willing": "No",
      "விருப்பம்": "Yes", "Willing": "Yes",
      "முடிவு செய்யப்படவில்லை": "Undecided" // or "" if not supported
    },
    // Education Qualification
    educationQualification: {
      "பொறியியல்": "Engineering",
      "மருத்துவம் (மருத்துவர்)": "Medicine (Doctor)",
      "M.C.A.": "M.C.A.",
      "M.B.A.": "Μ.Β.Α.",
      "சட்டப் படிப்பு": "Law Graduate",
      "பட்டதாரி": "Graduate",
      "கணினி பயன்பாடுகளுடன் பட்டதாரி": "Graduate with Computer Applications",
      "ஆசிரியர் பயிற்சியுடன் பட்டதாரி": "Graudate with Teacher Training",
      "முதுகலை பட்டதாரி": "Post Graduate",
      "கணினி பயன்பாடுகளுடன் முதுகலை": "Post Graduate with Computer Applications",
      "ஆசிரியர் பயிற்சியுடன் முதுகலை": "Post Graduate with Teacher Training",
      "ஆசிரியர் பயிற்சி": "Teacher Training",
      "B.Pharm": "B.Pharm",
      "B.Tech": "B.Tech",
      "B.Sc. Nursing": "B.Sc. Nursing",
      "D.Pharm": "D.Pharm",
      "பட்டயப்படிப்பு": "Diploma",
      "மேல்நிலை / S.S.L.C.": "Higher Secondary/ S.S.L.C.",
      "S.S.L.C. கீழே": "Below S.S.L.C",
      "மற்றவை": "Others"
    },
    // Occupation
    occupationBusiness: {
      "ஆசிரியர்": "Teacher",
      "மருத்துவர்": "Doctor",
      "பொறியாளர்": "Engineer",
      "வழக்கறிஞர்": "Lawyer",
      "செவிலியர்": "Nurse",
      "காவல் அதிகாரி": "Police Officer",
      "கணக்காளர்": "Accountant",
      "விவசாயி": "Farmer",
      "மென்பொருள் உருவாக்குநர்": "Software Developer",
      "எலக்ட்ரீஷியன்": "Electrician",
      "பிளம்பர்": "Plumber",
      "தச்சர்": "Carpenter",
      "ஓட்டுநர்": "Driver",
      "கடைக்காரர்": "Shopkeeper",
      "வியாபாரி": "Businessman",
      "சமையல்காரர்": "Chef / Cook",
      "சர்வர்": "Waiter",
      "மெக்கானிக்": "Mechanic",
      "தையல்காரர்": "Tailor",
      "முடிதிருத்துபவர்": "Barber",
      "விஞ்ஞானி": "Scientist",
      "பேராசிரியர்": "Professor",
      "கட்டிடக் கலைஞர்": "Architect",
      "வங்கி அதிகாரி": "Banker",
      "பத்திரிகையாளர்": "Journalist",
      "புகைப்படக் கலைஞர்": "Photographer",
      "வடிவமைப்பாளர்": "Designer",
      "சந்தைப்படுத்தல் நிர்வாகி": "Marketing Executive",
      "விற்பனையாளர்": "Salesman",
      "வரவேற்பாளர்": "Receptionist",
      "எழுத்தர்": "Clerk",
      "மேலாளர்": "Manager",
      "தொழில்நுட்பவியலாளர்": "Technician",
      "மருந்தாளுநர்": "Pharmacist",
      "பல் மருத்துவர்": "Dentist",
      "ஆய்வக தொழில்நுட்பவியலாளர்": "Lab Technician",
      "காவலாளி": "Security Guard",
      "ரியல் எஸ்டேட் முகவர்": "Real Estate Agent",
      "துப்புரவு பணியாளர்": "Cleaner",
      "கொத்தனார்": "Mason",
      "பெயிண்டர்": "Painter",
      "வெல்டர்": "Welder",
      "விமானி": "Pilot",
      "ராணுவ வீரர்": "Soldier",
      "சமூக சேவகர்": "Social Worker",
      "நூலகர்": "Librarian",
      "நிகழ்ச்சி அமைப்பாளர்": "Event Organizer",
      "தரவு ஆய்வாளர்": "Data Analyst",
      "காப்பீட்டு முகவர்": "Insurance Agent",
      "கால் சென்டர் நிர்வாகி": "Call Center Executive",
      "சிவில் இன்ஜினியர்": "Civil Engineer",
      "மெக்கானிக்கல் இன்ஜினியர்": "Mechanical Engineer",
      "எலக்ட்ரிக்கல் இன்ஜினியர்": "Electrical Engineer",
      "மென்பொருள் சோதனையாளர்": "Software Tester",
      "வலை உருவாக்குநர்": "Web Developer",
      "கிராஃபிக் வடிவமைப்பாளர்": "Graphic Designer",
      "ஆடை வடிவமைப்பாளர்": "Fashion Designer",
      "உள் அலங்கார வடிவமைப்பாளர்": "Interior Designer",
      "சுகாதார ஆய்வாளர்": "Health Inspector",
      "பிசியோதெரபிஸ்ட்": "Physiotherapist",
      "உளவியலாளர்": "Psychologist",
      "கால்நடை மருத்துவர்": "Veterinary Doctor",
      "தீயணைப்பு வீரர்": "Firefighter",
      "குடியேற்ற அதிகாரி": "Immigration Officer",
      "தபால்காரர்": "Postman",
      "டெலிவரி பாய்": "Delivery Boy",
      "வீட்டு பராமரிப்பு ஊழியர்": "Housekeeping Staff",
      "காசாளர்": "Cashier",
      "பயண முகவர்": "Travel Agent",
      "சுற்றுலா வழிகாட்டி": "Tour Guide",
      "ஐஏஎஸ் அதிகாரி": "IAS Officer",
      "ஐபிஎஸ் அதிகாரி": "IPS Officer",
      "நீதிபதி": "Judge",
      "வழக்கறிஞர் உதவியாளர்": "Advocate Assistant",
      "சுருக்கெழுத்தாளர்": "Stenographer",
      "தட்டச்சு செய்பவர்": "Typist",
      "மனிதவள நிர்வாகி": "HR Executive",
      "மனிதவள மேலாளர்": "HR Manager",
      "நிதி ஆய்வாளர்": "Financial Analyst",
      "பங்கு தரகர்": "Stock Broker",
      "வங்கி உதவியாளர்": "Banker Assistant",
      "கடன் அதிகாரி": "Loan Officer",
      "கொரியர் சேவை ஊழியர்": "Courier Service Staff",
      "கால் தொழில்நுட்பவியலாளர்": "Call Technician",
      "ஏசி மெக்கானிக்": "AC Mechanic",
      "ஆட்டோ ஓட்டுநர்": "Auto Driver",
      "பேருந்து நடத்துனர்": "Bus Conductor",
      "பேருந்து ஓட்டுநர்": "Bus Driver",
      "ரயில் டிக்கெட் பரிசோதகர்": "Train Ticket Examiner",
      "ரயில்வே ஊழியர்": "Railway Staff",
      "விமான நிலைய தரை ஊழியர்": "Airport Ground Staff",
      "விமானப் பணியாளர்": "Cabin Crew",
      "கடல்சார் பொறியாளர்": "Marine Engineer",
      "கப்பல் கேப்டன்": "Ship Captain",
      "உயிரியலாளர்": "Biologist",
      "வேதியியலாளர்": "Chemist",
      "புவியியலாளர்": "Geologist",
      "ஆய்வக உதவியாளர்": "Lab Assistant",
      "தொழிற்சாலை தொழிலாளி": "Factory Worker",
      "தொழில்முனைவோர்": "Entrepreneur"
    },
    // Country
    country: {
      "இந்தியா": "India",
      "அமெரிக்கா": "United States of America",
      "இலங்கை": "Sri Lanka",
      "மலேசியா": "Malaysia",
      "சிங்கப்பூர்": "Singapore",
      "ஆஸ்திரேலியா": "Australia",
      "கனடா": "Canada",
      "ஐக்கிய அரபு அமீரகம்": "United Arab Emirates",
      "இங்கிலாந்து": "United Kingdom",
      "சவுதி அரேபியா": "Saudi Arabia",
      "குவைத்": "Kuwait",
      "கத்தார்": "Qatar",
      "பிரான்ஸ்": "France",
      "ஜெர்மனி": "Germany"
    },
    // State
    state: {
      "தமிழ்நாடு": "Tamil Nadu",
      "கேரளா": "Kerala",
      "கர்நாடகா": "Karnataka",
      "ஆந்திரப் பிரதேசம்": "Andhra Pradesh",
      "தெலுங்கானா": "Telangana",
      "மகாராஷ்டிரா": "Maharashtra",
      "புதுச்சேரி": "Puducherry",
      "டெல்லி": "Delhi",
      "உத்தரப் பிரதேசம்": "Uttar Pradesh",
      // ... Map major states as needed based on translations
    },
    // District (Common Tamil names to English)
    district: {
       "சென்னை": "Chennai",
       "கோயம்புத்தூர்": "Coimbatore",
       "மதுரை": "Madurai",
       "திருச்சிராப்பள்ளி": "Tiruchirappalli",
       "சேலம்": "Salem",
       "திருநெல்வேலி": "Tirunelveli",
       "திருப்பூர்": "Tiruppur",
       "வேலூர்": "Vellore",
       "ஈரோடு": "Erode",
       "தூத்துக்குடி": "Thoothukudi",
       "திண்டுக்கல்": "Dindigul",
       "தஞ்சாவூர்": "Thanjavur",
       "சிவகாசி": "Sivakasi",
       "கரூர்": "Karur",
       "உதகமண்டலம்": "Udhagamandalam",
       "ஓசூர்": "Hosur",
       "நாகர்கோவில்": "Nagercoil",
       "காஞ்சிபுரம்": "Kanchipuram",
       "குமாரபாளையம்": "Kumarapalayam",
       "காரைக்குடி": "Karaikudi",
       "நெய்வேலி": "Neyveli",
       "கடலூர்": "Cuddalore",
       "கும்பகோணம்": "Kumbakonam",
       "திருவண்ணாமலை": "Tiruvannamalai",
       "பொள்ளாச்சி": "Pollachi",
       "ராஜபாளையம்": "Rajapalayam",
       "குடிமிப்பாளையம்": "Gudiyatham",
       "புதுக்கோட்டை": "Pudukkottai",
       "வாணியம்பாடி": "Vaniyambadi",
       "ஆம்பூர்": "Ambur",
       "நாகப்பட்டினம்": "Nagapattinam"
    },

    // Profile Created By
    profileCreatedBy: {
      "சுய": "Self",
      "பெற்றோர்": "Parents",
      "சகோதரன்": "Brother",
      "சகோதரி": "Sister",
      "நண்பர்": "Friend",
      "உறவினர்": "Relative",
      "மாமா": "Uncle",
      "அத்தை": "Aunt"
    },
    // Special Cases
    specialCases: {
      "ஆம்": "Yes",
      "இல்லை": "No"
    },
    // Zodiac Sign (Rasi) - Target is Hybrid "Tamil-English"
    zodiacSign: {
      "மேஷம்": "மேஷம்-Mesham", "Mesham": "மேஷம்-Mesham",
      "ரிஷபம்": "ரிஷபம்-Rishabam", "Rishabam": "ரிஷபம்-Rishabam",
      "மிதுனம்": "மிதுனம்-Mithunam", "Mithunam": "மிதுனம்-Mithunam",
      "கடகம்": "கடகம்-Kadagam", "Kadagam": "கடகம்-Kadagam",
      "சிம்மம்": "சிம்மம்-Simmam", "Simmam": "சிம்மம்-Simmam",
      "கன்னி": "கன்னி-Kanni", "Kanni": "கன்னி-Kanni",
      "துலாம்": "துலாம்-Thulam", "Thulam": "துலாம்-Thulam",
      "விருச்சிகம்": "விருச்சிகம்-Viruchigam", "Viruchigam": "விருச்சிகம்-Viruchigam",
      "தனுசு": "தனுசு-Dhanusu", "Dhanusu": "தனுசு-Dhanusu",
      "மகரம்": "மகரம்-Magaram", "Magaram": "மகரம்-Magaram",
      "கும்பம்": "கும்பம்-Kumbam", "Kumbam": "கும்பம்-Kumbam",
      "மீனம்": "மீனம்-Meenam", "Meenam": "மீனம்-Meenam"
    },
    // Ascendant (Lagnam) - Same Hybrid Target
    ascendant: {
      "மேஷம்": "மேஷம்-Mesham", "Mesham": "மேஷம்-Mesham",
      "ரிஷபம்": "ரிஷபம்-Rishabam", "Rishabam": "ரிஷபம்-Rishabam",
      "மிதுனம்": "மிதுனம்-Mithunam", "Mithunam": "மிதுனம்-Mithunam",
      "கடகம்": "கடகம்-Kadagam", "Kadagam": "கடகம்-Kadagam",
      "சிம்மம்": "சிம்மம்-Simmam", "Simmam": "சிம்மம்-Simmam",
      "கன்னி": "கன்னி-Kanni", "Kanni": "கன்னி-Kanni",
      "துலாம்": "துலாம்-Thulam", "Thulam": "துலாம்-Thulam",
      "விருச்சிகம்": "விருச்சிகம்-Viruchigam", "Viruchigam": "விருச்சிகம்-Viruchigam",
      "தனுசு": "தனுசு-Dhanusu", "Dhanusu": "தனுசு-Dhanusu",
      "மகரம்": "மகரம்-Magaram", "Magaram": "மகரம்-Magaram",
      "கும்பம்": "கும்பம்-Kumbam", "Kumbam": "கும்பம்-Kumbam",
      "மீனம்": "மீனம்-Meenam", "Meenam": "மீனம்-Meenam"
    },
    // Birth Star - Same Hybrid Target
    birthStar: {
      "அஸ்வினி": "அஸ்வினி-Ashwini", "Ashwini": "அஸ்வினி-Ashwini",
      "பாரணி": "பாரணி-Bharani", "Bharani": "பாரணி-Bharani",
      "கார்த்திகை": "கார்த்திகை-Karthigai", "Karthigai": "கார்த்திகை-Karthigai",
      "ரோகிணி": "ரோகிணி-Rohini", "Rohini": "ரோகிணி-Rohini",
      "மிருகசீரிஷம்": "மிருகசீரிஷம்-Mirugaseerisham", "Mirugaseerisham": "மிருகசீரிஷம்-Mirugaseerisham",
      "திருவாதிரை": "திருவாதிரை-Thiruvathirai", "Thiruvathirai": "திருவாதிரை-Thiruvathirai",
      "புனர்பூசம்": "புனர்பூசம்-Punarpoosam", "Punarpoosam": "புனர்பூசம்-Punarpoosam",
      "பூசம்": "பூசம்-Poosam", "Poosam": "பூசம்-Poosam",
      "ஆயிலியம்": "ஆயிலியம்-Ayilyam", "Ayilyam": "ஆயிலியம்-Ayilyam",
      "மகம்": "மகம்-Magam", "Magam": "மகம்-Magam",
      "பூரம்": "பூரம்-Pooram", "Pooram": "பூரம்-Pooram",
      "உத்திரம்": "உத்திரம்-Uthiram", "Uthiram": "உத்திரம்-Uthiram",
      "ஹஸ்தம்": "ஹஸ்தம்-Hastham", "Hastham": "ஹஸ்தம்-Hastham",
      "சித்திரை": "சித்திரை-Chithirai", "Chithirai": "சித்திரை-Chithirai",
      "சுவாதி": "சுவாதி-Swathi", "Swathi": "சுவாதி-Swathi",
      "விசாகம்": "விசாகம்-Visakam", "Visakam": "விசாகம்-Visakam",
      "அனுஷம்": "அனுஷம்-Anusham", "Anusham": "அனுஷம்-Anusham",
      "கேட்டை": "கேட்டை-Kettai", "Kettai": "கேட்டை-Kettai",
      "மூலம்": "மூலம்-Moolam", "Moolam": "மூலம்-Moolam",
      "புறாடம்": "புறாடம்-Pooradam", "Pooradam": "புறாடம்-Pooradam",
      "உத்திராடம்": "உத்திராடம்-Uthiradam", "Uthiradam": "உத்திராடம்-Uthiradam",
      "திருவோணம்": "திருவோணம்-Thiruvonam", "Thiruvonam": "திருவோணம்-Thiruvonam",
      "அவிட்டம்": "அவிட்டம்-Avittam", "Avittam": "அவிட்டம்-Avittam",
      "சதயம்": "சதயம்-Sadhayam", "Sadhayam": "சதயம்-Sadhayam",
      "பூரட்டாதி": "பூரட்டாதி-Poorattathi", "Poorattathi": "பூரட்டாதி-Poorattathi",
      "உத்திரட்டாதி": "உத்திரட்டாதி-Uthirattathi", "Uthirattathi": "உத்திரட்டாதி-Uthirattathi",
      "ரேவதி": "ரேவதி-Revathi", "Revathi": "ரேவதி-Revathi"
    },
    // Temple
    yourTemple: {
        "இளையாற்றங்குடி": "Ilayatrangudi",
        "மாத்தூர்": "Mathur",
        "வைரவன் கோவில்": "Vairavan Kovil",
        "நேமம் கோவில்": "Nemam Kovil",
        "இலுப்பைக்குடி": "Iluppakudi",
        "சூரக்குடி": "Soorakudi",
        "வேலங்குடி": "Velangudi",
        "இரணியூர்": "Iraniyur",
        "பிள்ளையார்பட்டி": "Pillaiyarpatti"
    },
    // Division
    yourDivision: {
        "பிரிவு இல்லை": "NO PIRIVU",
        "கழனி வாசக்குடையார்": "Kazhani Vaasarkkudaiyar",
        "கிங்கினிக்கூருடையார்": "Kinginikkurudaiyar",
        "ஒக்கூர் உடையார்": "Okkurudaiyar",
        "பட்டினசாமியார்": "Pattanasamiyar",
        "பெருசென்று உடையார்": "Perusenthrudaiyar",
        "சிறுசென்று உடையார்": "Sirusenthrudaiyar",
        "பெருமருதூர் உடையார்": "Perumaruthurudaiyar",
        "அரும்பாக்கூர்": "Arumbakkur",
        "கண்ணூர்": "Kannur",
        "கருப்பூர்": "Karuppur",
        "குளத்தூர்": "Kulathur",
        "மண்ணூர்": "Mannur",
        "மணலூர்": "Manalur",
        "உறையூர்": "Uraiyur",
        "மருதேந்திரபுரம்": "Maruthenthirapuram",
        "பெரிய வகுப்பு": "Periya vahuppu",
        "பிள்ளையார் வகுப்பு": "Pilliyar vahuppu",
        "தையனார் வகுப்பு": "Theyyanar vahuppu"
    },
    // Native Place
    nativePlace: {
        "அ. முத்து பட்டினம் – 630101": "A. Muthu Pattinam – 630101",
        "அ. சிறுவயல் – 630305": "A. Siruvayal – 630305",
        "அலவாக்கோட்டை – 630564": "Alavakkottai – 630564",
        "அமராவதிபுதூர் – 630301": "Amarapathiputhur – 630301",
        "அரிமளம் – 622201": "Arimalam – 622201",
        "அரியக்குடி – 630202": "Ariyakkudi – 630202",
        "ஆத்தங்குடி – 630101": "Athangudi – 630101",
        "ஆத்திக்காடு தெக்கூர் – 630201": "Athikadu Thekkur – 630201",
        "ஆவணிப்பட்டி – 630205": "Avanipatti – 630205",
        "சொக்கலிங்கம் புதூர் – 630101": "Chockalingam Pudur – 630101",
        "சொக்கநாதபுரம் – 630313": "Chockanatha Puram – 630313",
        "தேவகோட்டை – 630302": "Devakottai – 630302",
        "கடியாபட்டி – 622505": "Kadiapatty – 622505",
        "காளையார் மங்கலம் – 630557": "Kalaiyar Mangalam – 630557",
        "கல்லல் – 630300": "Kallal – 630300",
        "கல்லுப்பட்டி – 630306": "Kalluppatti – 630306",
        "கானாடுகாத்தான் – 630103": "Kanadukathan – 630103",
        "கண்டனூர் – 630104": "Kandanur – 630104",
        "கண்டரமாணிக்கம் – 630204": "Kandaramanickam – 630204",
        "கண்டவராயன் பட்டி – 630203": "Kandavarayan Patti – 630203",
        "காரைக்குடி – 630001": "Karaikudi – 630001",
        "கீழப்பூங்குடி – 630552": "Kilapungudi – 630552",
        "கீழசிவல்பட்டி – 630205": "Kilasaval Patti – 630205",
        "கொல்லங்குடி அழகபுரி – 630556": "Kollangudi Alagapuri – 630556",
        "கோனாப்பட்டு – 622503": "Konapet – 622503",
        "கொப்பனாபட்டி – 622401": "Koppanapatti – 622401",
        "கொத்தமங்கலம் – 630105": "Kothamangalam – 630105",
        "கோட்டையூர் – 630106": "Kottaiyur – 630106",
        "கோட்டையூர் அழகபுரி – 630106": "Kottaiyur Alagapuri – 630106",
        "குழிபிறை – 622402": "Kulipirai – 622402",
        "குருவிக்கொண்டான் பட்டி – 622409": "Kuruvikondan Patti – 622409",
        "மதகுபட்டி – 630553": "Madagupatti – 630553",
        "மகிபாலன் பட்டி – 630217": "Mahipalan Patti – 630217",
        "மானகிரி – 630307": "Managiri – 630307",
        "மங்கலம் – 630554": "Mangalam – 630554",
        "மேலசிவபுரி – 622403": "Melasivapuri – 622403",
        "முதலை பட்டி – 622409": "Mudalai Patti – 622409",
        "நாச்சாந்து பட்டி – 622404": "Nachandu Patti – 622404",
        "நாச்சியாபுரம் – 630207": "Nachiapuram – 630207",
        "நடராஜபுரம் – 630550": "Nataraja Puram – 630550",
        "நாட்டரசன்கோட்டை – 630556": "Nattarasan Kottai – 630556",
        "நேமத்தான் பட்டி – 630111": "Nemathan Patti – 630111",
        "நெற்குப்பை – 622405": "Nerkuppai – 622405",
        "ஓ. சிறுவயல் – 630208": "O. Siruvayal – 630208",
        "ஒக்கூர் – 630557": "Okkur – 630557",
        "பி. அழகபுரி – 630205": "P. Alagapuri – 630205",
        "பி. கருங்குளம் – 630204": "P. Karungulam – 630204",
        "பாகனேரி – 630558": "Paganeri – 630558",
        "பலவான்குடி – 630208": "Palavangudi – 630208",
        "பள்ளத்தூர் – 630107": "Pallathur – 630107",
        "பனங்குடி – 630555": "Panagudi – 630555",
        "பனைய பட்டி – 622406": "Panaya Patti – 622406",
        "பட்டமங்கலம் – 630310": "Pattamangalam – 630310",
        "புதுப்பட்டி – 622408": "Pudu Patti – 622408",
        "புதுவயல் – 630108": "Puduvayal – 630108",
        "பூலாங்குறிச்சி – 622413": "Pulangkurichi – 622413",
        "ராமச்சந்திரபுரம் – 622505": "Ramachandra Puram – 622505",
        "ராங்கியம் – 622409": "Rangiem – 622409",
        "ராயவரம் – 622506": "Rayavaram – 622506",
        "சக்கந்தி – 630562": "Sakkandhi – 630562",
        "செம்பனூர் – 630313": "Sembanur – 630313",
        "செவ்வூர் – 622417": "Sevvur – 622417",
        "சண்முகநாதபுரம் – 630314": "Shanmuganatha Puram – 630314",
        "சோழபுரம் – 630557": "Sholapuram – 630557",
        "சிறாவயல் – 630214": "Siravayal – 630214",
        "சிறுகூடல்பட்டி – 630215": "Sirukudal Patti – 630215",
        "தனிச்சாவூரணி – 630314": "Thanichavoorani – 630314",
        "தேனிப்பட்டி – 630211": "Thenipatti – 630211",
        "உலகம் பட்டி – 622410": "Ulagam Patti – 622410",
        "வி. லட்சுமிபுரம் – 622412": "V. Lakshimipuram – 622412",
        "வலைய பட்டி – 622411": "Valaya Patti – 622411",
        "வேகு பட்டி – 622407": "Vegu Patti – 622407",
        "வேந்தன் பட்டி – 622419": "Venthan Patti – 622419",
        "வெற்றியூர் – 630321": "Vetriyur – 630321",
        "விராச்சிலை – 622412": "Virachilai – 622412",
        "விராமதி – 630212": "Viramathi – 630212"
    } 
  };

  // 1. Check if mapping exists
  if (mappings[field] && mappings[field][normalizedValue]) {
    return mappings[field][normalizedValue];
  }

  // 2. Fallback: Return original value (it might already be English)
  return normalizedValue;
};
